apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qvh4ck455-nodejs
  janus-idp.io/tekton: qvh4ck455-nodejs
  backstage.io/kubernetes-id: qvh4ck455-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qvh4ck455-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
